pipeline:
  build:
    image: plugins/docker
    repo: kradalby/kubespace
    secrets: [ docker_username, docker_password ]
    tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
    when: 
        branch: master

  tag:
    image: plugins/docker
    repo: kradalby/kubespace
    secrets: [ docker_username, docker_password ]
    auto_tag: true
    when:
      event: tag

  deploy:
    image: quay.io/honestbee/drone-kubernetes
    deployment: kubespace-deployment
    repo: kradalby/kubespace
    container: kubespace-container
    namespace: kubespace
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
    tag:
      - ${DRONE_TAG} 
    when:
      event: tag

  notify:
    image: drillster/drone-email
    host: mail.ntnu.fap.no
    port: 25
    from: drone@drone.fap.no
    recipients: [ kradalby@kradalby.no ]
    when:
      status: [ success, changed, failure ]
